# calculating the median in days from self-removal TD
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'jruby'  and a.version_removed_name != 'not_removed'")
postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.version_removed_name != 'not_removed'")
data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
median(data1$epoch_time_to_remove/86400)


# calculating the median in days from non self-removal TD
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'jruby'  and a.version_removed_name != 'not_removed'")
postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author  and a.version_removed_name != 'not_removed'")
data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
median(data1$epoch_time_to_remove/86400)


# self-removal histogram
library(RPostgreSQL)
library(vioplot)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed'")
postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author = b.version_removed_author and a.project_name = 'jruby'  and a.version_removed_name != 'not_removed'")
data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
# hist(data1$epoch_time_to_remove/86400, xlab='Days to remove', main = paste('Self-removal histogram of ', data1$project_name[1]) )
vioplot(data1$epoch_time_to_remove/86400, names=c(data1$project_name[1]),   col="gold")
title(paste('Self-removal of ', data1$project_name[1]), ylab="Number of days")


# non self-removal histogram
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed'")
# postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed'")
postgresql <- dbSendQuery(con, "select a.project_name, a.epoch_time_to_remove from time_to_remove_td a, technical_debt_summary b where a.processed_comment_id = b.processed_comment_id and b.version_introduced_author != b.version_removed_author and a.project_name = 'jruby'  and a.version_removed_name != 'not_removed'")
data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
# hist(data1$epoch_time_to_remove/86400, xlab='Days to remove', main = paste('Non self-removal histogran of ', data1$project_name[1]) )
vioplot(data1$epoch_time_to_remove/86400, names=c(data1$project_name[1]),   col="gold")
title(paste('Non self-removal of ', data1$project_name[1]), ylab="Number of days")

# calculating the median in days for different types of td
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DESIGN' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DEFECT' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'apache-ant' and a.version_removed_name != 'not_removed' and a.comment_classification = 'TEST' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DESIGN' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'apache-jmeter' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DEFECT' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'jruby' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DESIGN' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'jruby' and a.version_removed_name != 'not_removed' and a.comment_classification = 'DEFECT' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'jruby' and a.version_removed_name != 'not_removed' and a.comment_classification = 'IMPLEMENTATION' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.project_name = 'jruby' and a.version_removed_name != 'not_removed' and a.comment_classification = 'TEST' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'DESIGN' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'DEFECT' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'IMPLEMENTATION' ")
# postgresql <- dbSendQuery(con, "select a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'TEST' ")

data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
median(data1$epoch_time_to_remove/86400)

# Different types of TD histogram
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', dbname='comment_classification', user='evermal', password='')
# postgresql <- dbSendQuery(con, "select 'Design Debt' as comment_classification, a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'DESIGN' ")
# postgresql <- dbSendQuery(con, "select 'Defect Debt' as comment_classification, a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'DEFECT' ")
# postgresql <- dbSendQuery(con, "select 'Requeriment Debt' as comment_classification, a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'IMPLEMENTATION' ")
postgresql <- dbSendQuery(con, "select 'Test Debt' as comment_classification, a.epoch_time_to_remove from time_to_remove_td a where a.version_removed_name != 'not_removed' and a.comment_classification = 'TEST' ")
data1 <- fetch(postgresql, n=-1)
dim(data1)
dbHasCompleted(postgresql)
# hist(data1$epoch_time_to_remove/86400, xlab='Days to remove', main = paste('Histogram of ', data1$comment_classification[1]))
vioplot(data1$epoch_time_to_remove/86400, names=c(data1$comment_classification[1]),   col="gold")
title(paste('Data distribution of ', data1$comment_classification[1]), ylab="Number of days")
